In [1]:
import pandas as pd
import numpy as np
import warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
customers = pd.read_excel("clean_customers.xlsx")
delivery = pd.read_excel("clean_delivery.xlsx")
orders = pd.read_excel("clean_orders.xlsx")
restaurants = pd.read_excel("clean_restaurants.xlsx")

In [3]:
customers.describe()

       Total_Orders  Average_Spend
count  22000.000000   22000.000000
mean       6.957682     322.838591
std       11.981829      87.904520
min        1.000000     102.000000
25%        3.000000     262.000000
50%        5.000000     315.000000
75%       10.000000     373.000000
max      271.000000     790.000000

In [4]:
#Outlier treatment Customers
numeric_cols = customers.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = customers[col].quantile(0.25)
    Q3 = customers[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    customers[col] = np.clip(customers[col], lower_bound, upper_bound)

print(customers.head())

  Customer_ID  Gender Age_Group           City Customer_Type  Total_Orders  \
0      C00001  Female     36-50          Urban           New           1.0
1      C00002  Female     36-50          Urban           New           2.0
2      C00003  Female     36-50  Metropolitian           New           2.0
3      C00004  Female     26-35          Urban           New           2.0
4      C00005    Male     18-25          Urban           New           1.0

   Average_Spend Preferred_Cuisine
0          375.0           Italian
1          320.0           Italian
2          450.0      North Indian
3          140.0      South Indian
4          282.0      North Indian

In [5]:
delivery.describe()

,Avg_Delivery_Speed_KMPH,Successful_Deliveries,Delayed_Deliveries,Avg_Customer_Rating,Delivery_Efficiency_Score
count,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000
mean,22.301773,14.305455,1.620909,4.644023,0.791368
std,5.581138,13.510531,2.079607,0.145359,0.116630
min,5.000000,0.000000,0.000000,3.700000,0.260000
25%,19.466769,4.000000,0.000000,4.583833,0.773000
50%,22.314730,9.000000,1.000000,4.650000,0.812000
75%,25.088396,23.250000,2.000000,4.719583,0.848000
max,40.000000,49.000000,12.000000,5.133333,1.000000

In [6]:
#Outlier treatment Delivery

numeric_cols = delivery.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = delivery[col].quantile(0.25)
    Q3 = delivery[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    delivery[col] = np.clip(delivery[col], lower_bound, upper_bound)

print(delivery.head())

  Delivery_Partner_ID   Partner_Name Vehicle_Type  Avg_Delivery_Speed_KMPH  \
0               D0001   Arjun Sharma      Scooter                23.310805
1               D0002   Vikram Gupta         Bike                21.378411
2               D0003  Vikram Chopra         Bike                16.008422
3               D0004   Kiran Sharma         Bike                15.686597
4               D0005   Arjun Sharma      Scooter                24.361525

   Successful_Deliveries  Delayed_Deliveries  Avg_Customer_Rating  \
0                     42                   5             4.634091
1                     25                   4             4.644444
2                      8                   1             4.637500
3                      9                   0             4.650000
4                      5                   0             4.460000

          Region  Delivery_Efficiency_Score
0  Metropolitian                      0.810
1  Metropolitian                      0.784
2          Urban                      0.754
3          Urban                      0.797
4  Metropolitian                      0.850

In [7]:
orders.describe()

,Order_Date,Order_Value,Delivery_Fee,Discount_Applied,Final_Amount,Delivery_Time_Minutes,Order_Rating
count,100000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2024-07-06 23:50:34.943999744,545.677920,35.685350,21.410950,559.952320,35.505560,4.023230
min,2023-01-01 00:00:00,200.000000,30.000000,0.000000,80.000000,25.000000,1.000000
25%,2023-10-10 00:00:00,429.000000,30.000000,0.000000,441.000000,32.000000,4.000000
50%,2024-07-11 00:00:00,542.000000,35.000000,0.000000,557.000000,35.000000,4.000000
75%,2025-04-04 00:00:00,656.000000,40.000000,30.000000,673.000000,39.000000,5.000000
max,2025-12-31 00:00:00,1200.000000,55.000000,150.000000,1250.000000,50.000000,5.000000
std,NaN,167.167972,6.172919,40.660466,172.104647,4.914946,0.927027

In [8]:
#Outlier treatment of Orders

numeric_cols = orders.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = orders[col].quantile(0.25)
    Q3 = orders[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    orders[col] = np.clip(orders[col], lower_bound, upper_bound)

print(orders.head())

  Order_ID Order_Date Customer_ID Restaurant_ID         Region  \
0  O809577 2025-04-12      C01162          R282  Metropolitian
1  O613973 2023-01-14      C05894          R181     Semi-Urban
2  O133055 2024-05-29      C02487          R303     Semi-Urban
3  O721755 2025-09-09      C01639          R409     Semi-Urban
4  O566596 2024-11-01      C05141          R358     Semi-Urban

  Delivery_Partner_ID  Order_Value  Delivery_Fee  Discount_Applied  \
0               D0496        423.0            30                 0
1               D0624        416.0            30                 0
2               D0044        465.0            50                 0
3               D0988        345.0            30                75
4               D1087        611.0            30                30

   Final_Amount Payment_Mode Order_Status  Delivery_Time_Minutes  \
0           453         Card    Delivered                   40.0
1           446       Wallet    Delivered                   32.0
2           515          Upi     Returned                   34.0
3           300         Cash    Delivered                   36.0
4           611         Card    Delivered                   31.0

   Order_Rating  Festival_Flag
0           4.0          False
1           4.0          False
2           4.0          False
3           3.0          False
4           3.0           True

In [9]:
restaurants.describe()

       Avg_Preparation_Time_Minutes  Avg_Rating  Order_Capacity_Per_Day
count                    550.000000  550.000000              550.000000
mean                      26.923636    4.623873               32.240000
std                        5.898163    0.195770               41.732305
min                       20.000000    3.500000                1.000000
25%                       22.000000    4.610000                1.000000
50%                       26.000000    4.640000               17.000000
75%                       29.000000    4.690000               36.750000
max                       40.000000    5.000000              136.000000

In [10]:
#Outlier treatment of Restaurants

numeric_cols = restaurants.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = restaurants[col].quantile(0.25)
    Q3 = restaurants[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    restaurants[col] = np.clip(restaurants[col], lower_bound, upper_bound)

print(restaurants.head())

  Restaurant_ID           City  Avg_Preparation_Time_Minutes  Avg_Rating  \
0          R001  Metropolitian                          27.0        4.64
1          R002     Semi-Urban                          39.5        4.49
2          R003          Urban                          24.0        4.71
3          R004          Urban                          23.0        4.71
4          R005          Urban                          25.0        4.72

   Order_Capacity_Per_Day  Restaurant_Name Cuisine_Type
0                  90.375   Restaurant_900    Fast Food
1                   1.000  Restaurant_1003      Italian
2                  30.000   Restaurant_671       Indian
3                  32.000   Restaurant_620    Fast Food
4                  28.000   Restaurant_926    Fast Food

In [11]:
import pandas as pd

# Function to check outliers for all numeric columns
def check_outliers_all(df, name):
    print(f"\n📊 Outlier Report for {name}\n")

    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        outliers = df[(df[col] < lower) | (df[col] > upper)]

        print(f"{col}: {len(outliers)} outliers")

# Run for all datasets
check_outliers_all(customers, "Customers")
check_outliers_all(delivery, "Delivery")
check_outliers_all(orders, "Orders")
check_outliers_all(restaurants, "Restaurants")

📊 Outlier Report for Customers

Total_Orders: 0 outliers
Average_Spend: 0 outliers

📊 Outlier Report for Delivery

Avg_Delivery_Speed_KMPH: 0 outliers
Successful_Deliveries: 0 outliers
Delayed_Deliveries: 0 outliers
Avg_Customer_Rating: 0 outliers
Delivery_Efficiency_Score: 0 outliers

📊 Outlier Report for Orders

Order_Value: 0 outliers
Delivery_Fee: 0 outliers
Discount_Applied: 0 outliers
Final_Amount: 0 outliers
Delivery_Time_Minutes: 0 outliers
Order_Rating: 0 outliers

📊 Outlier Report for Restaurants

Avg_Preparation_Time_Minutes: 0 outliers
Avg_Rating: 0 outliers
Order_Capacity_Per_Day: 0 outliers